<?php

/**
 * @file: Stackla Base module functions.
 */

/**
 * Implements hook_libraries_info().
 */
function stackla_libraries_info() {

  $libraries['stackla'] = array(
    'name' => 'Stackla',
    'vendor url' => 'http://stackla.com/',
    'download url' => 'http://stackla.com/api',
    'version' => 1,
    'files' => array(
      'php' => array('vendor/autoload.php'), //this can be a path to the file location like array('lib/simple.js')
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function stackla_menu() {
  $items = array();

  $items['admin/config/services/stackla'] = array(
    'title' => 'Stackla',
    'description' => 'Configure Stackla integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stackla_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer stackla'),
    'file' => 'stackla.admin.inc',
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM
  );

  $items['admin/config/services/stackla/test'] = array(
    'title' => 'Stackla: Test SDK integration',
    'description' => 'Test Stackla integration',
    'page callback' => 'stackla_test_api',
    'page arguments' => array('stackla_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer stackla'),
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM
  );

  $items['admin/config/services/stackla/accesscallback'] = array(
    'title' => 'Stackla: Access Callback',
    'description' => 'Callback for Stackal Oauth',
    'page callback' => 'stackla_outh_callback',
    'page arguments' => array('stackla_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer stackla'),
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function stackla_permission() {
  return array(
    'administer stackla' => array(
      'title' => t('Administer stackla'),
      'description' => t('Configure stackla module'),
    ),
  );
}

/**
 * Callback for a page to test API connectivity.
 */
function stackla_test_api() {
  $output = array();

//@todo: write something meaningful here.
  return $ouput;
}

/**
 * Callback for Oauth authentication.
 */
function stackla_outh_callback() {
  libraries_load('stackla');
  $output = array();

  $access_code = $_GET['code'];
  $client_id = variable_get('stackla_client_id');
  $host = variable_get('stackla_stack_oauth_host');
  $stack = variable_get('stackla_stack_name');
  $client_secret = variable_get('stackla_client_secret');
  $callback = 'http://' . $_SERVER['HTTP_HOST'] . '/admin/config/services/stackla/accesscallback';

  $credentials = new Stackla\Core\Credentials($host, null, $stack);
  $response = $credentials->generateToken($client_id, $client_secret, $access_code, $callback);

  if ($response === false) {
    drupal_set_message(t('Failed creating access token.'), 'error');
  }
  else {
    stackla_set_access_token($credentials->token);
    drupal_set_message(t('Successfully created access token'), 'status');
  }
  drupal_goto('admin/config/services/stackla');
}

/**
 * Check Stacka authentication.
 *
 * @return bool
 *  TRUE if authenticated.
 */
function stackla_is_authenticated() {
  if (stackla_get_access_token()) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Retrieve Stackla access token.
 *
 *  @return string
 *    The access token string or FALSE if not present.
 */
function stackla_get_access_token() {
  $encrypted_token = variable_get('stackla_access_token');
  if ($encrypted_token) {
    return decrypt($encrypted_token);
  }
  else {
    return FALSE;
  }
}

/**
 * Set Stackla access token.
 *  @param string $token
 *    The token string to set.
 *  @return boolean
 *    TRUE if successful.
 */
function stackla_set_access_token($token) {
  //@todo: add 2 way encryption
  $encrypted_token = encrypt($token);
  variable_set('stackla_access_token', $encrypted_token);
  return TRUE;
}

/**
 * Create a new Stackla Term
 *
 *  @param array $term
 *    Array of term data:
 *    'name' => The name of the term
 *    'network' => The machine name of the network eg 'twitter'.
 *    'type' => The query type machine name, eg 'hashtag'.
 *    'value' => They query value, eg 'bananas'.
 *  @return type
 *
 */
function stackla_create_term($term) {

  // Sim mode.
  if(variable_get('stackla_sim_mode') == 1) {
    watchdog('stackla', 'Simulating term creation. Values: <pre>@values</pre>', array(
      '@values' => print_r($term,TRUE),
    ), WATCHDOG_NOTICE);

    $new_term = new stdClass;
    $new_term->id = rand(1, 1000);

    return $new_term;
  }

  if(variable_get('stackla_debug_mode') == 1) {

    watchdog('stackla', 'Attempting to create term. Values: <pre>@values</pre>', array(
      '@values' => print_r($term,TRUE),
    ), WATCHDOG_NOTICE);
  }

  $stack = stackla_create_stack();

  $new_term = $stack->instance('term');

  // populating term properties
  $new_term->name = $term['name'];
  $new_term->display_name = $term['name'];
  $new_term->active = 1;
  $new_term->num_of_backfill = 0;
  $new_term->term = $term['value'];
  $new_term->type = $term['type'];
  $new_term->filter = '';
  $new_term->network = $term['network'];

  // Create the term
  try{
    $new_term->create();
  } catch (Exception $ex) {
    dpm($new_term->getErrors(),'error');
  }


  return $new_term;
}

function stackla_create_filter($filter) {
  if(variable_get('stackla_debug_mode') == 1) {

    watchdog('stackla', 'Attempting to create filter. Values: <pre>@values</pre>', array(
      '@values' => print_r($filter,TRUE),
    ), WATCHDOG_NOTICE);
  }

  $stack = stackla_create_stack();

  $new_filter = $stack->instance('filter');
  // Populate filter properties
  $new_filter->name = $filter['title'];
  $new_filter->networks = $filter['networks'];
  $new_filter->media = $filter['show_media'];
  $new_filter->sort = $filter['sort'];

  try{
    $new_filter->create();
  } catch (Exception $ex) {
    dpm($new_filter->getErrors(),'error');
  }

  return $new_filter;

}

function stackla_create_stack() {
  // Load the SDK.
  libraries_load('stackla');
  $stackla_variables = stackla_get_variables();

  if(variable_get('stackla_debug_mode') == 1) {

    watchdog('stackla', 'Attempting to create stack. Values: <pre>@values</pre>', array(
      '@values' => print_r($stackla_variables,TRUE),
    ), WATCHDOG_NOTICE);
  }


  // Stackla stack name
  $stack_name = $stackla_variables['stack_name'];

  // Stackla Credentials details
  $accessHost = $stackla_variables['oauth_host'];
  $accessToken = $stackla_variables['access_token']; // OAuth2 access_token
  $credentials = new \Stackla\Core\Credentials($accessHost, $accessToken, $stack_name);

  // Stackla API configs
  $stackHost = $stackla_variables['host_name'];
  $stack = new \Stackla\Api\Stack($credentials, $stackHost, $stack_name);

  return $stack;
}

function stackla_get_variables() {
  $credentials = array(
    'stack_name' => variable_get('stackla_stack_name'),
    'oauth_host' => variable_get('stackla_oauth_host'),
    'host_name' => variable_get('stackla_host_name'),
    'stack_name' => variable_get('stackla_stack_name'),
    'access_token' => stackla_get_access_token(),
  );
  return $credentials;
}
