<?php

/**
 * @file: Stackla Field functions.
 */

/**
 * Implements hook_field_info().
 */
function stackla_field_field_info() {
  $data = array(
    'stackla_field' => array(
      'label' => t('Stackla Widget'),
      'description' => t('Stackla Widget'),
      'default_widget' => 'stackla_field_widget',
      'default_formatter' => 'stackla_field_widget_formatter',
    ),
  );
  return $data;
}

/**
 * Implements hook_field_widget_info().
 */
function stackla_field_field_widget_info() {
  return array(
    'stackla_field_widget' => array(
      'label' => t('Stackla Field widget'),
      'field types' => array('stackla_field'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function stackla_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['widget_data']) ? unserialize($items[$delta]['widget_data']) : array();
  $widget = $element;
  $widget['#delta'] = $delta;

  if ($instance['widget']['type'] == 'stackla_field_widget') {

    $widget += array(
      '#type' => 'fieldset',
      '#element_validate' => array('stackla_field_element_validate'),
      // #delta is set so that the validation function will be able
      // to access external value information which otherwise would be
      // unavailable.
      '#delta' => $delta,
      '#prefix' => '<div id="st-fieldset">',
      '#suffix' => '</div>',
    );


    $widget['name'] = array(
      '#type' => 'textfield',
      '#title' => t('The title for your stackla widget'),
      '#default_value' => (!empty($value['name'])) ? $value['name'] : '',
    );

    $widget['terms'] = array(
      '#type' => 'fieldset',
      '#title' => t('Create Terms'),
      '#collapsed' => FALSE,
      '#collapsible' => FALSE,
    );

    $field_name = $field['field_name'];
    if (!empty($form_state['values'][$field_name]['und'][$delta]['widget_data'])) {
      $submitted_data = unserialize($form_state['values'][$field_name]['und'][$delta]['widget_data']);
      $social_elements = stackla_field_term_elements($submitted_data, $form_state);
      $filter_elements = stackla_field_filters($submitted_data, $form_state);
    }
    else {
      $social_elements = stackla_field_term_elements($value, $form_state);
      $filter_elements = stackla_field_filters($value, $form_state);
    }
    $widget['terms'] += $social_elements;

    $widget['filter_menu'] = array(
      '#type' => 'fieldset',
      '#title' => 'Create Filters',
      '#collapsed' => FALSE,
      '#collapsible' => FALSE,
    );

    $widget['filter_menu'] += $filter_elements;

    $widget['look_and_feel'] = array(
      '#type' => 'fieldset',
      '#title' => 'Look and Feel',
      '#collapsed' => FALSE,
      '#collapsible' => FALSE,
    );

    $widget['look_and_feel']['look_options'] = array(
      '#type' => 'radios',
      '#options' => array(
        'Option 1',
        'Option 2',
        'Option 3',
      ),
    );
  }

  $element['widget_data'] = $widget;
  return $element;
}

/**
 * Generate the filters widget form elements.
 * @param array $values
 *  the existing filter values
 * @param type $form_state
 *  The drupal $form_state (with'values' if this is an ajax rebuild).
 * @return string
 */
function stackla_field_filters($values, $form_state) {
  $elements = array();

  $highest_key = 0;

  // Check if a 'remove' button has been clicked
  $remove_index = 'empty';
  if (!empty($form_state['clicked_button'])) {
    $name_elements = explode('-', $form_state['clicked_button']['#name']);
    if ($name_elements[0] == 'filter') {
      $remove_index = intval($name_elements[2]);
    }
  }

  if (!empty($values['filter_menu'])) {
    $new_key = 0;
    foreach ($values['filter_menu'] as $key => $filter) {
      if ($new_key > $highest_key) {
        $highest_key = $new_key;
      }
      if (!empty($filter['title']) && ($key !== $remove_index)) {
        $elements += stackla_field_filter_element($new_key, $filter);
        $elements[$new_key]['remove'] = array(
          '#type' => 'button',
          '#value' => t('Remove filter'),
          '#name' => 'filter-remove-' . $new_key,
          '#ajax' => array(
            'callback' => 'stackla_field_ajax_widget_callback',
            'wrapper' => 'st-fieldset',
            'method' => 'replace',
            'effect' => 'fade',
          ),
        );
        $new_key++;
      }
    }
  }

  if (empty($elements[$highest_key]['title']['#default_value'])) {
    $elements += stackla_field_filter_element($highest_key, array());
  }

  $highest_key ++;
  $elements[$highest_key]['add_new'] = array(
    '#type' => 'button',
    '#value' => t('Add new filter'),
    '#name' => 'filter_add_new',
    '#ajax' => array(
      'callback' => 'stackla_field_ajax_widget_callback',
      'wrapper' => 'st-fieldset',
      'method' => 'replace',
      'effect' => 'fade',
    ),
  );

  return $elements;
}

/**
 *  Generate a single filter form element.
 * @param string $key
 *  the delta key
 * @param array $filter
 *  existing filter data (for populating default form values).
 * @return array
 *  the complete form element render array.
 */
function stackla_field_filter_element($key, $filter) {
  $elements = array();

  $elements[$key] = array(
    '#type' => 'fieldset',
  );

  //title
  $elements[$key]['title'] = array(
    '#title' => t('Title'),
    '#type' => 'textfield',
    '#default_value' => (!empty($filter['title'])) ? $filter['title'] : '',
  );


  //sort by
  $elements[$key]['sort'] = array(
    '#type' => 'select',
    '#options' => array(
      'source_created_at_desc' => t('Latest'),
      'score_desc' => t('Greatest'),
      'votes_desc' => t('Votes'),
      'random' => t('Random'),
    ),
    '#default_value' => (!empty($filter['sort'])) ? $filter['sort'] : '',
  );

  // show media
  $elements[$key]['show_media'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Show Media'),
    '#options' => array(
      'text' => t('Text only'),
      'image' => t('Images'),
      'video' => t('Video'),
    ),
    '#default_value' => (!empty($filter['show_media'])) ? $filter['show_media'] : array(),
  );

  // networks
  // @todo: limit these to networks chosen in terms.
  $elements[$key]['networks'] = array(
    '#title' => t('Networks'),
    '#type' => 'checkboxes',
    '#options' => array(
      'twitter' => t('Twitter'),
      'instagram' => t('Instagram'),
      'facebook' => t('Facebook'),
      'gplus' => t('Google+'),
      'youtube' => t('YouTube'),
    ),
    '#default_value' => (!empty($filter['networks'])) ? $filter['networks'] : array(),
  );

  if (!empty($filter['stackla_id'])) {
    $elements[$key]['stackla_id'] = array(
      '#type' => 'hidden',
      '#value' => $filter['stackla_id'],
    );
  }

  return $elements;
}

/**
 * Build social form elements from existing data.
 * @param array $values
 */
function stackla_field_term_elements($values, $form_state) {

  $term_types = array(
    'user' => array(
      'name' => t('User'),
      'prefix' => '@',
    ),
    'hashtag' => array(
      'name' => t('Hashtag'),
      'prefix' => '#'
    ),
    'page' => array(
      'name' => t('Page'),
      'prefix' => NULL,
    ),
    'search' => array(
      'name' => t('Search'),
      'prefix' => NULL,
    ),
  );


  $social_networks = array(
    'twitter' => array(
      'name' => t('Twitter'),
      'types' => array(
        'user',
        'hashtag',
        'search')
    ),
    'instagram' => array(
      'name' => t('Instagram'),
      'types' => array('hashtag', 'user'),
    ),
    'youtube' => array(
      'name' => t('YouTube'),
      'types' => array('user', 'search'),
    ),
    'facebook' => array(
      'name' => t('Facebook'),
      'types' => array('page'),
    ),
    'gplus' => array(
      'name' => t('Google+'),
      'types' => array('user'),
    ),
  );

  $network_options = array();

  foreach ($social_networks as $social_key => $social_network) {
    $network_options[$social_key] = $social_network['name'];
  }

  $initial_network_options = array(
    '0' => t('Select Network...'),
  );
  $initial_network_options += $network_options;

  // Check if a 'remove' button has been clicked
  $remove_index = 'empty';
  if (!empty($form_state['clicked_button'])) {
    $name_elements = explode('-', $form_state['clicked_button']['#name']);
    if ($name_elements[0] == 'social') {
      $remove_index = intval($name_elements[2]);
    }
  }

  $elements = array();
  $highest_key = 0;
  if (!empty($values['terms'])) {
    foreach ($values['terms'] as $key => $query) {
      if ($key > $highest_key) {
        $highest_key = $key;
      }
      if (!empty($query['network']) && $query['network'] != '0') {
        if ($key !== $remove_index) {
          $elements[$key] = array(
            '#type' => 'fieldset',
          );

          if (!empty($query['type'])) {
            $elements[$key]['name'] = array(
              '#title' => t('Term name'),
              '#type' => 'textfield',
              '#default_value' => (!empty($query['name'])) ? $query['name'] : '',
            );
          }

          // If the term has been created in Stackla, the network should no longer be
          // editable.
          if (!empty($query['stackla_id'])) {
            $elements[$key]['network'] = array(
              '#type' => 'hidden',
              '#value' => (!empty($query['network'])) ? $query['network'] : 0,
            );
            $elements[$key]['network_display'] = array(
              '#type' => 'markup',
              '#markup' => t('Network: @network', array(
                '@network' => (!empty($query['network'])) ? $network_options[$query['network']] : 0,
              )),
              '#prefix' => '<p>',
              '#suffix' => '</p>',
            );
          }
          else {
            $elements[$key]['network'] = array(
              '#type' => 'select',
              '#options' => $network_options,
              '#default_value' => (!empty($query['network'])) ? $query['network'] : 0,
              '#ajax' => array(
                'callback' => 'stackla_field_ajax_widget_callback',
                'wrapper' => 'st-fieldset',
                'method' => 'replace',
                'effect' => 'fade',
              ),
            );
          }

          $type_options = array();
          foreach ($social_networks[$query['network']]['types'] as $type_index) {
            $type_options[$type_index] = $term_types[$type_index]['name'];
          }

          // If the type is not yet selected, put an explanatory option in there.
          if (empty($query['type'])) {
            $type_options = array('Select type') + $type_options;
          }

          if (!empty($query['stackla_id'])) {
            $elements[$key]['type'] = array(
              '#type' => 'hidden',
              '#value' => (!empty($query['type'])) ? $query['type'] : 0,
            );

            $elements[$key]['type_display']  = array(
              '#type' => 'markup',
              '#markup' => t('Type: @type', array(
                '@type' => (!empty($query['type'])) ? $type_options[$query['type']] : 0,
              )),
              '#prefix' => '<p>',
              '#suffix' => '</p>',
            );

          }
          else {
            $elements[$key]['type'] = array(
              '#type' => 'select',
              '#options' => $type_options,
              '#default_value' => (!empty($query['type'])) ? $query['type'] : 0,
              '#ajax' => array(
                'callback' => 'stackla_field_ajax_widget_callback',
                'wrapper' => 'st-fieldset',
                'method' => 'replace',
                'effect' => 'fade',
              ),
            );
          }


          // If the term has been created in Stackla, the type should no
          // longer be editable.
          if (!empty($query['stackla_id'])) {
            $elements[$key]['type']['#value'] = (!empty($query['name'])) ? $query['name'] : '';
            $elements[$key]['type']['#description'] = t('You can not edit this.');
          }

          // Only show these fields after the type has been selected.
          if (!empty($query['type'])) {
            //
            $value_field_title = t('@network @type:', array(
              '@network' => $social_networks[$query['network']]['name'],
              '@type' => $term_types[$query['type']]['name'],
            ));
            $elements[$key]['value'] = array(
              '#title' => $value_field_title,
              '#type' => 'textfield',
              '#default_value' => (!empty($query['value'])) ? $query['value'] : '',
            );
            if (empty($query['value'])) {
              $elements[$key]['value']['#attributes'] = array(
                'placeholder' => t('Enter value'),
              );
            }


            if (empty($query['name'])) {
              $elements[$key]['name']['#attributes'] = array(
                'placeholder' => t('Enter a name for your term'),
              );
            }
          }

          // Hidden field for stackla id if present
          if (!empty($query['stackla_id'])) {
            $elements[$key]['stackla_id'] = array(
              '#type' => 'hidden',
              '#value' => $query['stackla_id'],
            );
          }



          $elements[$key]['remove'] = array(
            '#type' => 'button',
            '#value' => t('Remove'),
            '#name' => 'social-remove-' . $key,
            '#ajax' => array(
              'callback' => 'stackla_field_ajax_widget_callback',
              'wrapper' => 'st-fieldset',
              'method' => 'replace',
              'effect' => 'fade',
            ),
          );
        }
      }
    }
  }

  $new_select = array(
    'network' => array(
      '#type' => 'select',
      '#options' => $initial_network_options,
      '#default_value' => 0,
      //'#name' => 'stackla_social_new',
      '#ajax' => array(
        'callback' => 'stackla_field_ajax_widget_callback',
        'wrapper' => 'st-fieldset',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    ),
  );
  $elements[$highest_key + 1] = $new_select;

  return $elements;
}

/**
 * Ajax callback for widget form.
 */
function stackla_field_ajax_widget_callback($form, &$form_state) {
  // gets an array of the path of the triggering element.
  $parents = $form_state['triggering_element']['#array_parents'];

  // removes the triggering element name.
  array_pop($parents);
  array_pop($parents);
  array_pop($parents);

  // turns the array into a path on $form - i.e. $form['field_name']['und'][0]['your_element_name'];
  $element = drupal_array_get_nested_value($form, $parents);
  return $element;
}

/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function stackla_field_field_is_empty($item, $field) {
  return empty($item['widget_data']);
}

/**
 * Implements hook_field_validate().
 */
function stackla_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['widget_data'])) {
      //@todo: validate field data.
    }
  }
}

/**
 * Field element validation.
 */
function stackla_field_element_validate($element, &$form_state) {
  $delta = $element['#delta'];
  $field = $form_state['field'][$element['#field_name']][$element['#language']]['field'];
  $field_name = $field['field_name'];
  // Trying to add a new filter or query without setting the node name will
  // trigger a validation error.
  // Hack around this by setting the node title to the same as the widget title
  // if it's not already set.
  $errors = form_get_errors();
  if (!empty($errors['title']) && !empty($form_state['values'][$field_name][$element['#language']][$delta]['widget_data']['name'])) {
    stackla_field_filter_errors('title');
    $form_state['values']['title'] = $form_state['values'][$field_name][$element['#language']][$delta]['widget_data']['name'];
  }
  // Serialise the form data for storage.
  if (isset($form_state['values'][$field_name][$element['#language']][$delta]['widget_data'])) {
    $values = $form_state['values'][$field_name][$element['#language']][$delta]['widget_data'];
    $value = serialize($values);
    form_set_value($element, $value, $form_state);
  }
}

/**
 * Helper function, filter reset form errors for a specific message.
 *  @param string $element_name
 *    The name of the element to filter.
 */
function stackla_field_filter_errors($element_name) {
  $errors = form_get_errors();
  if ($errors) {
    // Clear errors.
    form_clear_error();
    // Clear error messages.
    $error_messages = drupal_get_messages('error');
    // Initialize an array where removed error messages are stored.
    $removed_messages = array();

    // Remove all errors originated by the 'foo][bar' element.
    foreach ($errors as $name => $error_message) {
      if ($name == $element_name) {
        $removed_messages[] = $error_message;
        unset($errors[$name]);
      }
    }

    // Reinstate remaining errors.
    foreach ($errors as $name => $error) {
      form_set_error($name, $error);
      // form_set_error() calls drupal_set_message(), so we have to filter out
      // these from the error messages as well.
      $removed_messages[] = $error;
    }

    // Reinstate remaining error messages (which, at this point, are messages that
    // were originated outside of the validation process).
    foreach (array_diff($error_messages['error'], $removed_messages) as $message) {
      drupal_set_message($message, 'error');
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function stackla_field_field_formatter_info() {
  return array(
    // This formatter just displays the hex value in the color indicated.
    'stackla_field_widget_formatter' => array(
      'label' => t('Stackla widget'),
      'field types' => array('stackla_field'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function stackla_field_theme($existing, $type, $theme, $path) {
  return array(
    'stackla_field' => array(
      'variables' => array(
        'data' => array(),
        'field_id' => 0,
      ),
      'template' => 'templates/stackla_field'
    ),
    'stackla_field_filters' => array(
      'variables' => array(
        'filters' => array(),
        'field_id' => 0,
      ),
    ),
  );
}

/**
 * Implements hook_preprocess_stackla_field().
 */
function stackla_field_preprocess_stackla_field(&$vars) {
  if (!empty($vars['data']['filter_menu'])) {
    $vars['filters'] = array(
      '#theme' => 'stackla_field_filters',
      '#filters' => $vars['data']['filter_menu'],
      '#field_id' => $vars['field_id'],
    );
  }
  drupal_add_css(drupal_get_path('module', 'stackla_field') . '/css/stackla_field.css');
}

/**
 * Filters list theme function.
 */
function theme_stackla_field_filters($variables) {
  $output = array();
  $list_class = '.stackla-filter-list.stackla-id-' . $variables['field_id'];
  $js = 'jQuery(\'' . $list_class . ' a\').click(function(){
    var filter = $(this).parent();
    StacklaFluidWidget.changeFilter(window.widgetId, filter.attr(\'data-filter\'));
});';


  $filters = $variables['filters'];
  $filter_list_elements = array();
  foreach ($filters as $delta => $filter) {
    if (!empty($filter['title'])) {
      // Generate a random filter id for now, replace this with actual data
      // once the SDK is available.
      $filter_id = $delta;

      // We don't use l() here because we don't want an href attribute on the
      // <a> tag.
      $filter_list_elements[] = sprintf('<a data-filter-id="%s">%s</a>', $filter_id, t($filter['title'])
      );
    }
  }
  if (!empty($filter_list_elements)) {
    $output = array(
      '#theme' => 'item_list',
      '#items' => $filter_list_elements,
      '#attributes' => array(
        'class' => array('stackla-filter-list stackla-id-' . $variables['field_id']), //add id here!
      ),
      // add attached js here.
      '#attached' => array(
        'js' => array(
          $js => array(
            'type' => 'inline',
            'scope' => 'footer',
          ),
        ),
        'css' => array(drupal_get_path('module', 'stackla_field') . '/css/stackla_field_filters.css'),
      ),
    );
  }

  $rendered_output = drupal_render($output);
  return $rendered_output;
}

/**
 * Implements hook_field_formatter_view().
 *
 */
function stackla_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $entity_id = entity_extract_ids($entity_type, $entity);
  $element = array();

  switch ($display['type']) {
    // Stackla field outputter.
    case 'stackla_field_widget_formatter':
      foreach ($items as $delta => $item) {
        $data = unserialize($item['widget_data']);
        $element[$delta] = array(
          '#theme' => 'stackla_field',
          '#data' => $data,
          '#field_id' => $entity_id[0] . $delta,
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_field_update().
 */
function stackla_field_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {
  dpm('update hook called');

  $field_name = $field['field_name'];
  $original_data = array();
  foreach ($entity->original->{$field_name}[$entity->language] as $entity_widget_delta => $entity_widget) {
    $original_data[$entity_widget_delta] = unserialize($entity_widget['widget_data']);
  }

  dpm($original_data, 'original data from supplied entity object');

  foreach ($items as $item_delta => $item) {
    $data = unserialize($item['widget_data']);
    dpm($data, 'data in update hook');

    // Compare terms in new data to original, call stackla if required.
    // Compare filters in new data to original, call stackla  if required.
    // Note we'll probably have to have some kind of sync/collision stuff in
    // here at some point.
    if (!empty($data['filter_menu'])) {
      foreach ($data['filter_menu'] as $filter_delta => $filter) {
        // If the filter is new, or the filter is changed, we need to do
        // somthing here.

        if (!empty($original_data[$item_delta]['filter_menu'][$filter_delta])) {
          $original_filter = $original_data[$item_delta]['filter_menu'][$filter_delta];
          if ($filter != $original_filter) {
            if (!empty($original_filter['stackla_id'])) {
              dpm('filter does not match original, run update here!!');
              dpm($filter, 'new filter data');
              dpm($original_filter, 'original filter data');
              $stackla_filter = stackla_field_prepare_filter($filter);
              if ($updated_filter = stackla_update_filter($stackla_filter, $original_filter)) {
                drupal_set_message(t('Filter @filter updated in Stackla', array(
                  '@filter' => $filter['title'],
                )));
              }
            }
            else {
              // the original filter does not have a stackla id, so
              // we need to create a new filter in stackla.
              if (stackla_field_filter_validate($filter)) {
                dpm($filter, 'orig filter does not have id, create in stackla');
                $new_filter = stackla_field_create_filter($filter);
                if ($new_filter->id) {
                  $data['filter_menu'][$filter_delta]['stackla_id'] = $new_filter->id;
                }
              }
            }
          }
        }
        else {
          // filter is new (does not exist in original entity), so we need
          // to create it in stackla.
          if (stackla_field_filter_validate($filter)) {
            dpm('Filter is new, create in stackla');
            $new_filter = stackla_field_create_filter($filter);
            if ($new_filter->id) {
              $data['filter_menu'][$filter_delta]['stackla_id'] = $new_filter->id;
            }
          }
        }
      }
    }
    // Serialise the changed data and store.
    $items[$item_delta]['widget_data'] = serialize($data);
  }
}

/**
 * Create a new filter in Stackla.
 *
 * @param array $filter
 */
function stackla_field_create_filter($filter) {
  $stackla_filter = stackla_field_prepare_filter($filter);
  if ($new_filter = stackla_create_filter($stackla_filter)) {
    if ($new_filter->id) {
      drupal_set_message(t('New filter @filter created in Stackla', array(
        '@filter' => $filter['title'],
      )));
    }
    else {
      // Log error, set message.
      drupal_set_message(t('Unable to create filter @filter', array(
        '@filter' => $filter['title'],
          )), 'error');
    }
  }
  return $new_filter;
}

/**
 * Implements hook_field_insert().
 */
function stackla_field_field_insert($entity_type, $entity, $field, $instance, $langcode, &$items) {
  dpm('insert hook called.');
  foreach ($items as $item_delta => $item) {
    $data = unserialize($item['widget_data']);
    // Process new terms.
    if (!empty($data['terms'])) {
      foreach ($data['terms'] as $term_delta => $term) {
        if (stackla_field_term_data_validate($term)) {
          // submit the term to Stackla.
          if ($new_term = stackla_create_term($term)) {
            // Add the returned ID to the widget data.
            $data['terms'][$term_delta]['stackla_id'] = $new_term->id;
            drupal_set_message(t('New term @term created in Stackla', array(
              '@term' => $term['name'],
            )));
          }
          else {
            // Log error, set message.
            drupal_set_message(t('Unable to create term @term', array(
              '@term' => $term['name'],
                )), 'error');
          }
        }
      }
    }

    if (!empty($data['filter_menu'])) {
      foreach ($data['filter_menu'] as $filter_delta => $filter) {
        if (stackla_field_filter_validate($filter)) {
          $stackla_filter = stackla_field_prepare_filter($filter);
          if ($new_filter = stackla_create_filter($stackla_filter)) {
            if ($new_filter->id) {
              $data['filter_menu'][$filter_delta]['stackla_id'] = $new_filter->id;
              drupal_set_message(t('New filter @filter created in Stackla', array(
                '@filter' => $filter['title'],
              )));
            }
            else {
              // Log error, set message.
              drupal_set_message(t('Unable to create filter @filter', array(
                '@filter' => $filter['title'],
                  )), 'error');
            }
          }
        }
      }
    }

    // Serialise the changed data and store.
    $items[$item_delta]['widget_data'] = serialize($data);
  }
}

/**
 * Takes a filter array from the field and convert to a
 * format ready to send to Stackla.
 */
function stackla_field_prepare_filter($filter) {
  $stackla_filter = array(
    'name' => $filter['title'],
    'networks' => array_values($filter['networks']),
    'media' => array_values($filter['show_media']),
    'sort' => $filter['sort'],
  );

  if (!empty($filter['stackla_id'])) {
    $stackla_filter['stackla_id'] = $filter['stackla_id'];
  }

  return $stackla_filter;
}

function stackla_field_filter_validate($filter) {
  if (empty($filter['title'])) {
    return FALSE;
  }

  if (empty($filter['sort'])) {
    return FALSE;
  }

  if (empty($filter['show_media'])) {
    return FALSE;
  }

  if (empty($filter['networks'])) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Utility function: validate a submitted term.
 * @param type $term
 */
function stackla_field_term_data_validate($term) {

  // Term must have a name.
  if (empty($term['name'])) {
    return FALSE;
  }

  // Term must have a network
  if (empty($term['network'])) {
    return FALSE;
  }

  if (empty($term['value'])) {
    return FALSE;
  }

  if (empty($term['type'])) {
    return FALSE;
  }

  return TRUE;
}
